### PR TITLE
Fix Cloudflare Captcha Issue

### PR DESCRIPTION
**Pull request by rainner**
Give this a go, tested and works here on localhost with node 10.15.3.

### CODE REVIEW

**Comment by alexzaworski** [comment]
This looks fine to me and does seem to work. I was reading through [cloudscraper's](https://github.com/codemanki/cloudscraper) docs and it looks like cloudflare expects a 5s delay, I really have no idea how to proceed here.

A 5s delay on every api call seems untenable but we're in bad shape if the app gets blocked by some heuristic.

@natewiley your call on if we wanna just merge this and call it good. If you prefer I start taking action on PRs that's fine too, though it makes sense for you to make commits to master imo for deployments.

There're actually whitespace issues with this PR (mixed spaces/tabs too) but I think they should be handled separately via `.editorconfig`, `eslint`, etc (I can help with this)

**Comment by natewiley** [comment]
@rainner Nice work! I appreciate you taking the time to get this working. 

@alexzaworski I noticed some mixed spaces/etc issues too, feel free to help out there. Also feel free to take action on PRs in future, I trust your judgement.

**Comment by rainner** [comment]
Sorry about the whitespace, I disabled any whitespace trimming options in my text editor (VSCode) to preserve the original as much as possible but I guess something went wrong there.

**Comment by chriscoyier** [comment]
Looks like it's down again right now... Can someone tell if it's our fault at CodePen and you're getting that Cloudflare block page? Or if it's something else?

We can't officially support this API, but we don't wanna break stuff on you if we don't have to.

**Comment by alexzaworski** [comment]
Looks like things got bumped from the 'just wait a sec' interstitial to a captcha :( Don't think there's any way to bypass that via node

**Comment by alexzaworski** [comment]
While this is a total bummer, I did find this while doing some research which made me laugh

https://github.com/Kamikadze4GAME/cloudflare-bypasser/blob/5fe0098be8151add827bd54d92cb320406fd85b2/lib/bypasser.js#L155-L159

**Comment by chriscoyier** [comment]
You can control the User Agent of the request right? Perhaps we can alter that to include "cpv2api" and we could look for that.

**Comment by alexzaworski** [comment]
Yup we're setting UA manually at the moment

Doesn't creating exceptions like that cause problems for you folks from actual bad actors though?

**Pull request merged**
